name: Java CI

on:
  # Scheduled runs
  schedule:
    - cron: '0 0 * * *'

  push:
      branches:
        - master
      tags:
        - v*

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew clean assembleDebug
      - run: tree
      - name: Archive builds
        uses: actions/upload-artifact@v2
        with:
          name: settings_apk-debug.apk
          path: ./app/build/outputs/apk/settings_apk-debug.apk
